/*
 * This source file was generated by the Gradle 'init' task
 */
package exemple;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PanierTest {
    
    @Test void initPanierVide() {
        var test = new Panier();

        assertTrue(test.estVide());
        assertEquals(0.0, test.getTotalHT(), 0.01);
        assertEquals(0.0, test.getTotalTTC(.2), 0.01);
    }
    // Cas Usuel
    @Test void ajouterProduitAbsentDuPanierVide() {
        var test = new Panier();

        test.ajouter(new Panier.Ligne("foo", 2, 50.0));

        assertFalse(test.estVide());
        assertEquals(100.0, test.getTotalHT(), 0.01);
        assertEquals(120.0, test.getTotalTTC(.2), 0.01);
    }
    @Test void ajouterProduitAbsentDunPanierRempli() {
        
    }
    @Test void ajouterProduitDejaExistantMemePrix() {
        
    }
    @Test void ajouterProduitDejaExistantPrixDifferent() {
        
    }
    @Test void ajouterProduitExistantQuantiteNegative() {
        
    }
    // Cas extrême
    @Test void ajouterProduitExistantQuantiteNegativeQte0() {
        
    }
    // Cas d'erreur
    @Test void ajouterProduitInexistantQuantite() {
        
    }
    @Test void ajouterProduitExistantQuantiteNegativeTropGrande() {
        
    }
}
